export const CHANGE_PASSWORD = "authentication:CHANGE_PASSWORD"
export const LOGOUT = "authentication:LOGOUT"
export const RESET_PASSWORD_PROPS = "authentication:RESET_PASSWORD_PROPS"
export const SET_LOGIN_ERROR = "authentication:SET_LOGIN_ERROR"
export const SET_REGISTER_ERROR = "authentication:SET_REGISTER_ERROR"
export const SET_USER_DATA = "authentication:SET_USER_DATA"
export const SET_VERIFICATION_ERROR = "authentication:SET_VERIFICATION_ERROR"
export const VERIFY_EMAIL = "authentication:VERIFY_EMAIL"

export const GET_MEME = "meme:GET_MEME"
export const RESET_MEME_TO_INITIAL = "meme:RESET_MEME_TO_INITIAL"
export const SET_MEME_FETCH_ERROR = "meme:SET_MEME_FETCH_ERROR"
export const UPDATE_MEME = "meme:UPDATE_MEME"
export const UPDATE_MEME_IMG = "meme:UPDATE_MEME_IMG"

export const SEARCH_ARTISTS = "search:SEARCH_ARTISTS"
export const SEARCH_MEMES = "search:SEARCH_MEMES"
export const SEARCH_TEMPLATES = "search:SEARCH_TEMPLATES"

export const GET_TEMPLATE = "template:GET_TEMPLATE"
export const SET_TEMPLATE_FETCH_ERROR = "template:SET_TEMPLATE_FETCH_ERROR"
export const UPDATE_TEMPLATE = "template:UPDATE_TEMPLATE"

export const CHANGE_PROFILE_PIC = "user:CHANGE_PROFILE_PIC"
export const GET_USER = "user:GET_USER"
export const GET_USER_MEMES = "user:GET_USER_MEMES"
export const GET_USER_TEMPLATES = "user:GET_USER_TEMPLATES"
export const SET_USER_FETCH_ERROR = "user:SET_USER_FETCH_ERROR"
export const SET_USER_MEMES_FETCH_ERROR = "user:SET_USER_MEMES_FETCH_ERROR"
export const SET_USER_TEMPLATES_FETCH_ERROR = "user:SET_USER_TEMPLATES_FETCH_ERROR"
export const UPDATE_USER = "user:UPDATE_USER"
